### ISSUE TITLE
PostgreSQL connection via environment variables 

### ISSUE THREAD

**Issue by tseabra** [JerryCai/arachni#5]
Hi @JerryCai 

First of all thanks for this great tool. 
Since arachni software supports PostgreSQL it would be great to be able to use it with your docker image. 
Is this something you are working on ?
It is definatly something I can do quickly and send you a PR if you want. 

Thanks

**Comment by JerryCai** [comment]
Hi @tseabra,
Thanks a lot for your great idea to make this image more useful. Sure, We will be glad to accept your PR. Thank you!
